// Class Colors constant
// Class: Depredador
#define ZP_COLOR_DEPREDADOR_R 255
#define ZP_COLOR_DEPREDADOR_G 180
#define ZP_COLOR_DEPREDADOR_B 60
// Class: Nemesis
#define ZP_COLOR_NEMESIS_R 255
#define ZP_COLOR_NEMESIS_G 0
#define ZP_COLOR_NEMESIS_B 255
// Class: Zombie
#define ZP_COLOR_ZOMBIE_R 0
#define ZP_COLOR_ZOMBIE_G 150
#define ZP_COLOR_ZOMBIE_B 0
// Class: Survivor
#define ZP_COLOR_SURVIVOR_R 0
#define ZP_COLOR_SURVIVOR_G 255
#define ZP_COLOR_SURVIVOR_B 255
// Class: Survivor
#define ZP_COLOR_HUMAN_R 0
#define ZP_COLOR_HUMAN_G 0
#define ZP_COLOR_HUMAN_B 150

// Spect Color
#define ZP_COLOR_SPECT 255

// ITEMS
// ZOMBIE MADNESS
#define ZP_COLOR_MADNESS_R 150
#define ZP_COLOR_MADNESS_G 0
#define ZP_COLOR_MADNESS_B 0

// PULSE SHOCK
#define ZP_COLOR_PULSES_R 0
#define ZP_COLOR_PULSES_G 255
#define ZP_COLOR_PULSES_B 255